spring:
  datasource:
    username: peter
    password: 820517
    url: jdbc:mysql://localhost:3306/house
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


